//
//  GrapeVariatiesList.swift
//  Vinishko
//
//  Created by mttm on 01.09.2023.
//

import Foundation

struct Grape {
    static let varietiesList = [
        "grape_cabernet_sauvignon",
        "grape_merlot",
        "grape_chardonnay",
        "grape_sauvignon_blanc",
        "grape_pinot_noir",
        "grape_syrah",
        "grape_riesling",
        "grape_zinfandel",
        "grape_tempranillo",
        "grape_sangiovese",
        "grape_malbec",
        "grape_grenache",
        "grape_viognier",
        "grape_pinot_gris",
        "grape_nebbiolo",
        "grape_gewurztraminer",
        "grape_semillon",
        "grape_chenin_blanc",
        "grape_barbera",
        "grape_albarino",
        "grape_petit_verdot",
        "grape_mourvedre",
        "grape_trebbiano",
        "grape_touriga_nacional",
        "grape_vermentino",
        "grape_carmenere",
        "grape_verdejo",
        "grape_tannat",
        "grape_aglianico",
        "grape_fiano",
        "grape_arneis",
        "grape_vernaccia",
        "grape_tinta_roriz",
        "grape_moscato",
        "grape_lambrusco",
        "grape_dolcetto",
        "grape_torrontes",
        "grape_godello",
        "grape_mencia",
        "grape_macabeo",
        "grape_bonarda",
        "grape_falanghina",
        "grape_saperavi",
        "grape_roussanne",
        "grape_friulano",
        "grape_melon_de_bourgogne",
        "grape_counoise",
        "grape_auxerrois",
        "grape_verdelho",
        "grape_furmint",
        "grape_marsanne",
        "grape_cinsault",
        "grape_garganega",
        "grape_pinot_blanc",
        "grape_picpoul",
        "grape_gruner_veltliner",
        "grape_corvina",
        "grape_cannonau",
        "grape_arinto",
        "grape_aligote",
        "grape_nerello_mascalese",
        "grape_pedro_ximenez",
        "grape_carignan",
        "grape_dornfelder",
        "grape_insolia",
        "grape_agiorgitiko",
        "grape_xinomavro",
        "grape_antao_vaz",
        "grape_rolle",
        "grape_norton",
        "grape_assyrtiko",
    ]
}
